Merged latest ethmonitor changes into ethmonitor-custom. Added fail_resource_when_interface_down parameter.

diff --git a/heartbeat/ethmonitor-custom b/heartbeat/ethmonitor-custom
--- a/heartbeat/ethmonitor-custom
+++ b/heartbeat/ethmonitor-custom
@@ -7,7 +7,7 @@
 #
 #	Transfered from Ipaddr2 into ethmonitor by Alexander Krauth
 #
-# Copyright (c) 2011 Robert Euhus, Alexander Krauth, Lars Marowsky-Brée
+# Copyright (c) 2011 Robert Euhus, Alexander Krauth, Lars Marowsky-Br�e
 #					All Rights Reserved.
 #
 # This program is free software; you can redistribute it and/or modify
@@ -49,20 +49,46 @@
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
 
+# Parameter defaults
+
+OCF_RESKEY_interface_default=""
+OCF_RESKEY_name_default=""
+OCF_RESKEY_multiplier_default="1"
+OCF_RESKEY_repeat_count_default="5"
+OCF_RESKEY_repeat_interval_default="10"
+OCF_RESKEY_pktcnt_timeout_default="5"
+OCF_RESKEY_arping_count_default="1"
+OCF_RESKEY_arping_timeout_default="1"
+OCF_RESKEY_arping_cache_entries_default="5"
+OCF_RESKEY_link_status_only_default="false"
+OCF_RESKEY_fail_resource_when_interface_down_default="false"
+
+: ${OCF_RESKEY_interface=${OCF_RESKEY_interface_default}}
+: ${OCF_RESKEY_name=${OCF_RESKEY_name_default}}
+: ${OCF_RESKEY_multiplier=${OCF_RESKEY_multiplier_default}}
+: ${OCF_RESKEY_repeat_count=${OCF_RESKEY_repeat_count_default}}
+: ${OCF_RESKEY_repeat_interval=${OCF_RESKEY_repeat_interval_default}}
+: ${OCF_RESKEY_pktcnt_timeout=${OCF_RESKEY_pktcnt_timeout_default}}
+: ${OCF_RESKEY_arping_count=${OCF_RESKEY_arping_count_default}}
+: ${OCF_RESKEY_arping_timeout=${OCF_RESKEY_arping_timeout_default}}
+: ${OCF_RESKEY_arping_cache_entries=${OCF_RESKEY_arping_cache_entries_default}}
+: ${OCF_RESKEY_link_status_only=${OCF_RESKEY_link_status_only_default}}
+: ${OCF_RESKEY_fail_resource_when_interface_down=${OCF_RESKEY_fail_resource_when_interface_down_default}}
+
 #######################################################################
 
 meta_data() {
 	cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="ethmonitor-custom">
-<version>1.2</version>
+<resource-agent name="ethmonitor-custom" version="1.2">
+<version>1.0</version>
 
 <longdesc lang="en">
 Monitor the vitality of a local network interface.
 
 A CUSTOM VERSION OF THE 'ethmonitor' RESOURCE AGENT. UNLIKE THE STANDARD 'ethmonitor' RESOURCE AGENT,
-THE MONITOR OPERATION OF THIS RESOURCE WILL FAIL IF THE INTERFACE IS DOWN.
+THIS RESOURCE AGENT ALLOWS FOR THE MONITOR OPERATION OF THIS RESOURCE TO FAIL IF THE INTERFACE IS DOWN.
 
 You may set up this RA as a clone resource to monitor the network interfaces on different nodes, with the same interface name.
 This is not related to the IP address or the network on which a interface is configured.
@@ -94,7 +120,7 @@ The ethmonitor works in 3 different modes to test the interface vitality.
 The name of the network interface which should be monitored (e.g. eth0).
 </longdesc>
 <shortdesc lang="en">Network interface name</shortdesc>
-<content type="string" default=""/>
+<content type="string" default="${OCF_RESKEY_interface_default}"/>
 </parameter>
 
 <parameter name="name" unique="1">
@@ -102,7 +128,7 @@ The name of the network interface which should be monitored (e.g. eth0).
 The name of the CIB attribute to set.  This is the name to be used in the constraints. Defaults to "ethmonitor-'interface_name'".
 </longdesc>
 <shortdesc lang="en">Attribute name</shortdesc>
-<content type="string" default=""/>
+<content type="string" default="${OCF_RESKEY_name_default}"/>
 </parameter>
 
 <parameter name="multiplier" unique="0" >
@@ -110,7 +136,7 @@ The name of the CIB attribute to set.  This is the name to be used in the constr
 Multiplier for the value of the CIB attriobute specified in parameter name. 
 </longdesc>
 <shortdesc lang="en">Multiplier for result variable</shortdesc>
-<content type="integer" default="1"/>
+<content type="integer" default="${OCF_RESKEY_multiplier_default}"/>
 </parameter>
 
 <parameter name="repeat_count">
@@ -118,7 +144,7 @@ Multiplier for the value of the CIB attriobute specified in parameter name.
 Specify how often the interface will be monitored, before the status is set to failed. You need to set the timeout of the monitoring operation to at least repeat_count * repeat_interval
 </longdesc>
 <shortdesc lang="en">Monitor repeat count</shortdesc>
-<content type="integer" default="5"/>
+<content type="integer" default="${OCF_RESKEY_repeat_count_default}"/>
 </parameter>
 
 <parameter name="repeat_interval">
@@ -126,7 +152,7 @@ Specify how often the interface will be monitored, before the status is set to f
 Specify how long to wait in seconds between the repeat_counts.
 </longdesc>
 <shortdesc lang="en">Monitor repeat interval in seconds</shortdesc>
-<content type="integer" default="10"/>
+<content type="integer" default="${OCF_RESKEY_repeat_interval_default}"/>
 </parameter>
 
 <parameter name="pktcnt_timeout">
@@ -134,7 +160,7 @@ Specify how long to wait in seconds between the repeat_counts.
 Timeout for the RX packet counter. Stop listening for packet counter changes after the given number of seconds.
 </longdesc>
 <shortdesc lang="en">packet counter timeout</shortdesc>
-<content type="integer" default="5"/>
+<content type="integer" default="${OCF_RESKEY_pktcnt_timeout_default}"/>
 </parameter>
 
 <parameter name="arping_count">
@@ -143,7 +169,7 @@ Number of ARP REQUEST packets to send for every IP.
 Usually one ARP REQUEST (arping) is send
 </longdesc>
 <shortdesc lang="en">Number of arpings per IP</shortdesc>
-<content type="integer" default="1"/>
+<content type="integer" default="${OCF_RESKEY_arping_count_default}"/>
 </parameter>
 
 <parameter name="arping_timeout">
@@ -152,7 +178,7 @@ Time in seconds to wait for ARP REQUESTs (all packets of arping_count).
 This is to limit the time for arp requests, to be able to send requests to more than one node, without running in the monitor operation timeout.
 </longdesc>
 <shortdesc lang="en">Timeout for arpings per IP</shortdesc>
-<content type="integer" default="1"/>
+<content type="integer" default="${OCF_RESKEY_arping_timeout_default}"/>
 </parameter>
 
 <parameter name="arping_cache_entries">
@@ -160,7 +186,7 @@ This is to limit the time for arp requests, to be able to send requests to more 
 Maximum number of IPs from ARP cache list to check for ARP REQUEST (arping) answers. Newest entries are tried first.
 </longdesc>
 <shortdesc lang="en">Number of ARP cache entries to try</shortdesc>
-<content type="integer" default="5"/>
+<content type="integer" default="${OCF_RESKEY_arping_cache_entries_default}"/>
 </parameter>
 
 <parameter name="infiniband_device">
@@ -184,7 +210,15 @@ For infiniband devices, this is the port to monitor.
 Only report success based on link status. Do not perform RX counter or arping related connectivity tests.
 </longdesc>
 <shortdesc lang="en">link status check only</shortdesc>
-<content type="boolean" default="false" />
+<content type="boolean" default="${OCF_RESKEY_link_status_only_default}" />
+</parameter>
+
+<parameter name="fail_resource_when_interface_down">
+<longdesc lang="en">
+Fail the resource when the monitor operations detects that the interface is down.
+</longdesc>
+<shortdesc lang="en">Fail the resource when interface is down</shortdesc>
+<content type="boolean" default="${OCF_RESKEY_fail_resource_when_interface_down_default}" />
 </parameter>
 
 </parameters>
@@ -209,8 +243,8 @@ is_interface() {
 	#
 	# List interfaces but exclude FreeS/WAN ipsecN virtual interfaces
 	#
-	local iface=`$IP2UTIL -o -f link addr show | grep " $1:" \
-		| cut -d ' ' -f2 | tr -d ':' | sort -u | grep -v '^ipsec[0-9][0-9]*$'`
+	local iface=`$IP2UTIL -o -f link addr show | grep -e " $1[:@]" \
+		| cut -d ' ' -f2 | tr -d ':' | cut -d '@' -f1 | sort -u | grep -v '^ipsec[0-9][0-9]*$'`
 		[ "$iface" != "" ]
 }
 
@@ -257,7 +291,6 @@ if_init() {
 		esac
 	fi
 
-	: ${OCF_RESKEY_multiplier:="1"}
 	if ! ocf_is_decimal "$OCF_RESKEY_multiplier"; then
 		ocf_exit_reason "Invalid OCF_RESKEY_multiplier [$OCF_RESKEY_multiplier]"
 		exit $OCF_ERR_CONFIGURED
@@ -275,22 +308,18 @@ if_init() {
 		ocf_exit_reason "Invalid OCF_RESKEY_repeat_interval [$REP_INTERVAL_S]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_pktcnt_timeout:="5"}
 	if ! ocf_is_decimal "$OCF_RESKEY_pktcnt_timeout"; then
 		ocf_exit_reason "Invalid OCF_RESKEY_pktcnt_timeout [$OCF_RESKEY_pktcnt_timeout]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_count:="1"}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_count"; then
 		ocf_exit_reason "Invalid OCF_RESKEY_arping_count [$OCF_RESKEY_arping_count]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_timeout:="1"}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_timeout"; then
 		ocf_exit_reason "Invalid OCF_RESKEY_arping_timeout [$OCF_RESKEY_arping_count]"
 		exit $OCF_ERR_CONFIGURED
 	fi
-	: ${OCF_RESKEY_arping_cache_entries:="5"}
 	if ! ocf_is_decimal "$OCF_RESKEY_arping_cache_entries"; then
 		ocf_exit_reason "Invalid OCF_RESKEY_arping_cache_entries [$OCF_RESKEY_arping_cache_entries]"
 		exit $OCF_ERR_CONFIGURED
@@ -466,7 +495,6 @@ if_monitor() {
 	
 	local mon_rc=$OCF_NOT_RUNNING
 	local attr_rc=$OCF_NOT_RUNNING
-	local monitor_rc=$OCF_NOT_RUNNING
 	local runs=0
 	local start_time
 	local end_time
@@ -493,22 +521,30 @@ if_monitor() {
 	ocf_log debug "Monitoring return code: $mon_rc"
 	if [ $mon_rc -eq $OCF_SUCCESS ]; then
 		set_cib_value 1
-		monitor_rc=$?
+		attr_rc=$?
 	else
 		ocf_log err "Monitoring of $OCF_RESOURCE_INSTANCE failed."
 		set_cib_value 0
 
-		# If the interface check failed but the attribute was set successfully, exit with $OCF_ERR_GENERIC.
-		# Otherwise, exit with the error return code from setting the attribute.
-		case "$?" in
-			0) monitor_rc=$OCF_ERR_GENERIC ;;
-			*) monitor_rc=$? ;;
-		esac
+		## If we have been configured to fail the resource when the monitoring fails, use the custom behaviour, as described below:
+		## The monitor operation will fail if the interface is down, allowing the on-fail meta attribute to be used to control what
+		## happens when an interface is down.
+		if ocf_is_true "$OCF_RESKEY_fail_resource_when_interface_down"; then
+			# If the interface check failed but the attribute was set successfully, exit with $OCF_ERR_GENERIC.
+			# Otherwise, exit with the error return code from setting the attribute.
+			case "$?" in
+				0) attr_rc=$OCF_ERR_GENERIC ;;
+				*) attr_rc=$? ;;
+			esac
+		## Use the normal ethmonitor behaviour, as described below:
+		## The resource should not fail, if the interface is down. It should fail, if the update of the CIB variable has errors.
+		## To react on the interface failure you must use constraints based on the CIB variable value, not on the resource itself.
+		else
+			attr_rc=$?
+		fi
 	fi
 	
-	# The monitor operation will fail if the interface is down, allowing the on-fail meta attribute to be used to control what
-	# happens when an interface is down. This behaviour differs from the standard ethmonitor resource agent.
-	exit $monitor_rc
+	exit $attr_rc
 }
 
 if_stop()
